<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Windows Settings -->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <!-- Linux Settings -->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!-- Use Avalonia instead of WPF -->
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.1" />
    <None Include="ProjectTemplates\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
